preset: recommended

risky: false

enabled:

disabled:
  - concat_without_spaces
  - phpdoc_summary

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  path:
    - "aop"