language: php

matrix:
  include:
    - php: 5.4
    - php: 5.6
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
    - php: 7.2

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - composer dumpautoload -o
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require symfony/console; fi
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_success:
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
      php php-coveralls.phar -v;
    fi

notifications:
  email: never
