language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: CODING_STANDARD=1
    - php: 7.2
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require symfony/console; fi
  - composer dumpautoload -o
  - if [[ $CODING_STANDARD == "" ]]; then vendor/bin/phpunit $PHPUNIT_FLAGS; else composer check-cs; fi

after_success:
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
      php php-coveralls.phar -v;
    fi

notifications:
  email: never
