language: php

matrix:
  include:
    - php: 5.4
    - php: 5.6
    - php: 7.1
    - php: 7.2

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - composer dumpautoload -o
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require symfony/console; fi
  - vendor/bin/phpunit $PHPUNIT_FLAGS --coverage-text

notifications:
  email: never
