language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

install:
  - composer update --prefer-dist
  - bin/genrsa tests

script:
  - vendor/bin/phpunit

after_success:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
      php php-coveralls.phar -v;
    fi

notifications:
  email: never
