language: php

matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS=--prefer-lowest
    - php: 5.6
    - php: 7.1

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS --coverage-text

notifications:
  email: never
