name: run-tests

on:
  push:
    branches: [ v2.0 ]
  pull_request:
    branches: [ v2.0 ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.4 ]
        stability: [ prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, openssl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name : Cache Composer packages
        id : composer-cache
        uses : actions/cache@v2
        with :
          path : vendor
          key : ${{ matrix.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys : |
            ${{ matrix.os }}-php-

      - name: Install dependencies
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --dev

      - name: Genearate RSA PEM
        run: bin/genrsa tests

      - name: Execute tests
        run: vendor/bin/phpunit
